create table if not exists public.submissions (
    id bigint generated by default as identity primary key,
    student_name text not null,
    student_group text not null,
    submitted_at timestamp without time zone not null,
    deadline timestamp without time zone not null,
    on_time boolean not null,
    qcm_score integer not null,
    qcm_total integer not null,
    lab_score integer not null,
    lab_total integer not null,
    total_score integer not null,
    max_score integer not null,
    percentage numeric not null,
    grade text not null,
    qcm_answers jsonb not null default '{}'::jsonb,
    lab_answers jsonb not null default '{}'::jsonb,
    lab_code_answers jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

-- Upgrade an existing table created before group capture was added.
alter table public.submissions
add column if not exists student_group text not null default '';

alter table public.submissions enable row level security;

-- Recommended for this Streamlit app:
-- Use a Supabase service-role key as SUPABASE_KEY on the server, keep it only in Streamlit secrets,
-- and do not expose it in browser code or a public repository.
--
-- If you use the anon key instead, create a narrow insert/select policy below
-- and accept that anyone with the anon key may submit/read according to policy.
-- create policy "allow anon insert submissions"
-- on public.submissions for insert
-- to anon
-- with check (true);
--
-- create policy "allow anon read leaderboard"
-- on public.submissions for select
-- to anon
-- using (true);
